version: 2
jobs:
  build:
    docker:
    - image: circleci/python:3.6.6-node
    working_directory: ~/singnet/snet-cli
    environment:
      TRIGGER_BUILD_BRANCH: master
    steps:
    - run:
        name: Install tools and ipfs
        command: |
            cd ..
            sudo apt-get update
            sudo apt-get -y install libudev-dev libusb-1.0-0-dev curl jq
            # install IPFS
            wget https://dist.ipfs.io/go-ipfs/v0.4.17/go-ipfs_v0.4.17_linux-amd64.tar.gz
            tar xvfz go-ipfs_*.tar.gz
            sudo cp ./go-ipfs/ipfs /usr/local/bin
    - checkout
    - run:
        name: Install snet-cli 
        command: |
            ./scripts/blockchain install
            sudo pip3 install -e .
    - run:
        name: Install platform-contracts from master
        command: |
            # Install platform-contracts (from master)
            # we will deploy contracts from test/utils/reset_enviroment.sh
            cd ..
            git clone https://github.com/singnet/platform-contracts
            cd platform-contracts
            npm install
            npm install ganache-cli
            npm run-script compile
    - run:
        name: Unit tests
        command: |
            bash -ex test/utils/run_all_unit.sh
    - run:
        name: Functional tests
        command: |
            bash -ex test/utils/run_all_functional.sh
    - run:
        name: Trigger platform-pipeline build
        command: |
          if [ "$CIRCLE_BRANCH" == "$TRIGGER_BUILD_BRANCH" ]
          then
            curl -u ${CIRCLECI_PLATFORM_PIPELINE_TOKEN}: \
              -d build_parameters[CIRCLE_JOB]=build \
              -d build_parameters[PARENT_PROJECT_REPONAME]="$CIRCLE_PROJECT_REPONAME" \
              -d build_parameters[PARENT_BRANCH]="$CIRCLE_BRANCH" \
              -d build_parameters[PARENT_BUILD_URL]="$CIRCLE_BUILD_URL" \
              https://circleci.com/api/v1.1/project/github/singnet/platform-pipeline/tree/${TRIGGER_BUILD_BRANCH}
          fi
